# Generated by Django 3.0.7 on 2020-06-30 10:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='UUID')),
                ('name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('balance', models.IntegerField(default=0, verbose_name='Баланс')),
                ('hold', models.PositiveIntegerField(default=0, verbose_name='Замороженные средства')),
                ('is_opened', models.BooleanField(default=True, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Счёт',
                'verbose_name_plural': 'Счёта',
            },
        ),
    ]
